bases:
    root:
        patterns:
            - base/root.gotmpl
    list:
        base: root
        patterns:
            - base/list.gotmpl
    entity:
        base: root
        patterns:
            - base/entity.gotmpl
pages:
    index:
        base: root
        patterns:
            - index.gotmpl
entities:
    assertions:
        entity:
            base: entity
            patterns:
                - assertions/assertion.gotmpl
        pages:
            index:
                base: list
    citations:
        entity:
            base: entity
            patterns:
                - citations/citation.gotmpl
        pages:
            index:
                base: list
    events:
        entity:
            base: entity
            patterns:
                - events/event.gotmpl
        pages:
            index:
                base: list
    media:
        entity:
            base: entity
            patterns:
                - media/media.gotmpl
        pages:
            index:
                base: list
    persons:
        entity:
            base: entity
            patterns:
                - persons/person.gotmpl
        pages:
            index:
                base: root
                patterns:
                    - persons/index.gotmpl
    places:
        entity:
            base: entity
            patterns:
                - places/place.gotmpl
        pages:
            index:
                base: list
    relationships:
        entity:
            base: entity
            patterns:
                - relationships/relationship.gotmpl
        pages:
            index:
                base: list
    repositories:
        entity:
            base: entity
            patterns:
                - repositories/repository.gotmpl
        pages:
            index:
                base: list
    sources:
        entity:
            base: entity
            patterns:
                - sources/source.gotmpl
        pages:
            index:
                base: list
